class Shoot:

    # Initialize our hand.
    def __init__(self, opponent, win_state):
        # Your opponent, A = Rock, B = Paper, C = Scissors.
        self.opponent = opponent
        # The win state, X = Lose, Y = Draw, Z = Win.
        self.win_state = win_state
        # A dictionary that looks up our score using the opponent's hand and our desired win state.
        self.win_states = {'X':{'A':3, 'B':1, 'C':2}
                          ,'Y':{'A':4, 'B':5, 'C':6}
                          ,'Z':{'A':8, 'B':9, 'C':7}
                          }


    # Define our string, in this case I want to display the number of points the current matchup yields.
    def __str__(self):
        return f'Points from matchup: {self.win_states[self.win_state][self.opponent]}'

    # Return the points generated by the current matchup.
    def resolve_round(self):
        return self.win_states[self.win_state][self.opponent]
